global:
  scrape_interval: 15s # Як часто забирати дані (стандарт - 15 сек)

scrape_configs:
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node_exporter:9100'] # Ім'я контейнера та порт агента
